vim.opt.autoread = true                                         -- Reload a file if changed outside vim
vim.opt.clipboard = "unnamedplus"                               -- Use system clipboard
vim.opt.cmdheight = 2                                           -- Command line height
vim.opt.completeopt = {"menuone", "noselect"}
vim.opt.cursorline = true
vim.opt.expandtab = false                                       -- I like tabs
vim.opt.fileencoding = "utf-8"
vim.opt.hlsearch = true
vim.opt.ignorecase = true
vim.opt.list = true
vim.opt.listchars = {tab="> ", lead="-", nbsp="+", trail="-"}
vim.opt.mouse = "a"
vim.opt.number = true
vim.opt.pumheight = 15
vim.opt.scrolloff = 8
vim.opt.shiftwidth = 0                                          -- Use tab width as indent
vim.opt.showtabline = 2
vim.opt.signcolumn = "yes"
vim.opt.smartcase = true
vim.opt.smartindent = true
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.swapfile = true
vim.opt.tabstop = 4
vim.opt.timeoutlen = 1500
vim.opt.title = true
vim.opt.undofile = true
vim.opt.updatetime = 400
vim.opt.writebackup = true
